version: "3"

services:
  zabbix-mysql:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=1q2w3e4r
      # - MYSQL_USER=zabbix
      # - MYSQL_PASSWORD=1q2w3e4r
    volumes:
      - "./mysql/init.d/allow-permission.sql:/docker-entrypoint-initdb.d/allow-permission.sql"
  zabbix-backend:
    image: zabbix/zabbix-server-mysql:alpine-latest
    depends_on:
      - zabbix-mysql
    restart: unless-stopped
    ports:
      - 10051:10051
    environment:
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=1q2w3e4r
      - DB_SERVER_HOST=zabbix-mysql
  zabbix-frontend:
    image: zabbix/zabbix-web-apache-mysql:alpine-latest
    depends_on:
      - zabbix-backend
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=1q2w3e4r
      - ZBX_SERVER_HOST=zabbix-backend
      - PHP_TZ=Asia/Bangkok
      - DB_SERVER_HOST=zabbix-mysql
  